---
title: "GSM_01"
author: "Ricky S"
date: "`r Sys.Date()`"
output: html_document
---


```{r Load Package}
library(dplyr)
library(Seurat)
library(patchwork)
```

```{r Read Data}
A6.data <- Read10X(data.dir = 'C:/Users/ricky/Code/SciP/GSM/6A', gene.column = 1)
A6 <- CreateSeuratObject(counts = A6.data, project = "CeliacD", min.cells = 3, min.features = 200)
A6
```

```{r Metadata}
A6@meta.data$condition <- "control"
A6@meta.data$batch <- "6A"
```

```{r Read Data}
A8.data <- Read10X(data.dir = 'C:/Users/ricky/Code/SciP/GSM/8A', gene.column = 1)
A8 <- CreateSeuratObject(counts = A8.data, project = "CeliacD", min.cells = 3, min.features = 200)
A8
```

```{r Metadata}
A8@meta.data$condition <- "coeliac"
A8@meta.data$batch <- "8A"
```

```{r Merge}
Merge_obj <- merge(A6, y=c(A8), add.cell.ids=c("1","2"))
Merge_obj
```

```{r Split RNA}
#It's actually already split
Merge_obj[['RNA']] <- split(Merge_obj[['RNA']], f = Merge_obj$batch)
Merge_obj
```

```{r Filter}
Merge_obj[["percent.mt"]] <- PercentageFeatureSet(Merge_obj, pattern = "^MT-")


VlnPlot(Merge_obj, features = c('nFeatureRNA','nCountRNA','percent.mt'),ncol=3)

Merge_obj <- subset(Merge_obj, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
```